Stranger6667/jsonschema

.github/workflows/build.yml
Tests will need some extra work, dev server, etc
=> chore: Add CI

.github/workflows/build.yml, tests/test_suite.rs
The goal of this PR is to ensure that tests are executed as part of the defined github workflow.
Bonus points:
* ensure that tests are executed during PR as well
* ensure that no regressions are present on Draft6 (as it is marked as _fully supported_)
=> Run tests in github workflow

.github/workflows/build.yml, README.md
=> chore: Add code coverage reporting

src/keywords/additional_properties.rs, src/keywords/mod.rs
=> fix: Bug for `additionalProperties: false`

Cargo.toml, benches/jsonschema.rs
=> chore: Refactor benchmark

CHANGELOG.md, src/schemas.rs
=> feat: Implement "Default" for "Draft"

README.md
=> Make README Examples runnable

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/meta_schemas/draft4.json, jsonschema/meta_schemas/draft6.json, jsonschema/meta_schemas/draft7.json, jsonschema/src/compilation/options.rs
=> feat: Meta schemas for JSON Schema drafts 4, 6, and 7

jsonschema/benches/jsonschema.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/pattern_properties.rs, jsonschema/src/keywords/properties.rs, jsonschema/src/lib.rs
=> Fix validators overlap

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/src/keywords/format.rs, jsonschema/src/keywords/pattern.rs, jsonschema/src/lib.rs, jsonschema/tests/test_suite.rs
=> fix: Incorrect handling of `\w` and `\W` character groups in `pattern` keywords

jsonschema/src/error.rs, jsonschema/src/lib.rs, jsonschema/src/primitive_type.rs
Allows users to handle and format their own errors. These changes are presented as an alternative to custom formatting.
=> feat: Made error types public

jsonschema/src/keywords/required.rs
This addresses #190. Thank you so much, please let me know if I need to make further adjustments.
=> fix: Include all validation errors for required properties

jsonschema/src/compilation/mod.rs, jsonschema/src/error.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/mod.rs, jsonschema/src/keywords/required.rs
By reducing the number of quotes there.
=> chore: Make error messages more readable

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/src/keywords/all_of.rs, jsonschema/src/keywords/format.rs, jsonschema/src/keywords/pattern.rs, jsonschema/src/keywords/required.rs, jsonschema/src/paths.rs
=> Fix `regex` pattern incorrectly rejecting supported regex patterns

CHANGELOG.md, jsonschema/src/compilation/options.rs, jsonschema/src/keywords/format.rs
=> feat: Support for custom 'format' validators

jsonschema/src/compilation/mod.rs, jsonschema/src/keywords/additional_items.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/all_of.rs, jsonschema/src/keywords/any_of.rs, jsonschema/src/keywords/contains.rs, jsonschema/src/keywords/dependencies.rs, jsonschema/src/keywords/if_.rs, jsonschema/src/keywords/items.rs, jsonschema/src/keywords/mod.rs, jsonschema/src/keywords/not.rs, jsonschema/src/keywords/one_of.rs, jsonschema/src/keywords/pattern_properties.rs, jsonschema/src/keywords/properties.rs, jsonschema/src/keywords/property_names.rs, jsonschema/src/keywords/ref_.rs, jsonschema/src/validator.rs
=> refactor: Move validator formatting to `validator.rs`

bindings/python/src/lib.rs, jsonschema/src/compilation/mod.rs, jsonschema/src/error.rs, jsonschema/src/keywords/properties.rs, jsonschema/src/paths.rs
changes in `PathChunk` are backward-incompatible
=> Minor optimizations

bindings/python/CHANGELOG.md, bindings/python/src/lib.rs, bindings/python/tests-py/test_jsonschema.py
=> fix(python): Inaccurate schema path in validation error messages

CHANGELOG.md, jsonschema/Cargo.toml, jsonschema/src/keywords/format.rs
=> feat: added duration format validation

README.md, jsonschema/src/lib.rs
Just a short update to the notes on stability, based on the conversation in #215.
=> docs: add/update stability notes

bindings/python/CHANGELOG.md, bindings/python/src/ffi.rs, bindings/python/src/lib.rs, bindings/python/src/ser.rs, bindings/python/src/types.rs, bindings/python/tests-py/test_jsonschema.py
=> feat: convert python enum into raw values before validating

CHANGELOG.md, bindings/python/Cargo.lock, jsonschema/Cargo.toml, jsonschema/src/paths.rs
=> chore: Bump `itoa` to `1.0`

jsonschema/Cargo.toml
- fancy_regex from 0.8.0 to 0.9.0
- uuid from 0.8.2 to 1.0.0
=> chore: update dependencies

bindings/python/src/ser.rs, bindings/python/tests-py/test_jsonschema.py
=> fix(python): Fix SystemError when non-str dict key provided #386

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/src/keywords/ref_.rs
=> fix: incorrect schema_path in errors from $ref

README.md
Thanks for mentioning the project!
The custom keyword & formats are working like a charm and I wanted to update the example using the latest API...
=> docs: update qsv integration

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema/Cargo.toml, crates/jsonschema/src/keywords/format.rs, crates/jsonschema/tests/suite.rs
=> chore: Extend email validation

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema/src/keywords/pattern.rs
=> perf: Cache regular expressions

.github/workflows/ci.yml, CHANGELOG.md, README.md, crates/jsonschema/Cargo.toml, crates/jsonschema/src/lib.rs, crates/jsonschema/src/retriever.rs, crates/jsonschema/src/validator.rs, crates/jsonschema/tests/suite.rs
=> chore: Run tests on WASM

CHANGELOG.md, crates/jsonschema/src/keywords/ref_.rs
=> fix: Missing annotations from by-reference applicators

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/README.md, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema-py/tests-py/test_suite.py
=> feat(py): Config option to enable format validation

crates/jsonschema/src/retriever.rs
=> fix: Resolving file paths on Windows

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/tests-py/test_suite.py, crates/jsonschema/src/keywords/unevaluated_items.rs, crates/jsonschema/tests/suite.rs
=> feat: Support $recursiveRef & $dynamicRef in unevaluatedItems

CHANGELOG.md, crates/jsonschema/src/lib.rs
Resolves #614 
It still feels suboptimal, I'll re-visit it a bit later
=> chore: Re-export referencing::Error

crates/jsonschema-py/README.md
=> docs: Add validate_formats=True to raise error in demonstration

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/Cargo.toml, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py
=> feat(python): Added `ValidationError.kind` and `ValidationError.instance` attributes

crates/jsonschema/src/paths.rs
I've been working on improving validation for [BlueBuild](https://github.com/blue-build)'s recipe format, and the way we do that is to find the byte offset in the file via the location specified by the errors reported by this crate. We need to iterate over the segments of the `Location` object so that we can follow the AST in the Yaml parser. We created our own wrapper around `Location` to have this support, but we'd like to have this available upstream for other's to use.
=> feat: Allow iterating over `LocationSegment`'s from a `Location`

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-referencing/src/uri.rs, crates/jsonschema/src/keywords/ref_.rs
=> fix: Fragment references within $id-anchored subschemas

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema/src/keywords/ref_.rs
=> fix: Resolving relative references with fragments

CHANGELOG.md, crates/jsonschema-cli/Cargo.toml, crates/jsonschema-cli/src/main.rs, crates/jsonschema-cli/tests/cli.rs, crates/jsonschema-cli/tests/snapshots/cli__relative_resolution-2.snap, crates/jsonschema-cli/tests/snapshots/cli__relative_resolution.snap, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/README.md, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema-py/tests-py/test_masking.py, crates/jsonschema-py/tests-py/test_meta.py, crates/jsonschema-py/tests-py/test_registry.py, crates/jsonschema-py/tests-py/test_retriever.py, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/options.rs, crates/jsonschema/src/retriever.rs
=> feat: Add `base_uri`
