draft/src/lib.rs, tests/test_suite.rs
The goal of this PR is to remove the presence of implicit imports in the procedural macro implementation.
=> No implicit imports in proc macro

.github/workflows/build.yml
The goal is to avoid running the same checks twice in pull requests
=> chore: Run CI on pull requests & pushes to master

draft/Cargo.toml, draft/src/lib.rs, tests/test_suite.rs
This is needed because there might be integration tests for which we would
like to ignore the outcome (for example it is an optional test).
In order to achieve this result the procedural macro has been rewritten to exploit
`syn` and `quote` capabilities (enhanced parsing as well as less string concatenations).
Additionally the new testing methods:
*  do rely on 2 base methods `test_valid` and `test_invalid` and this allow less binary code to be generated and
* are under `quote` macro but essentially is fully correct rust code so eventual future modifications are simples
* do rely on users input to exclude test cases (so no changes into `draft` project for excluding including new tests)
* are divided  into modules so it will be simpler to run the integration tests for a specific draft …
=> feat: Add test_to_exclude capability into test_draft procedural macro

Cargo.toml, src/error.rs, src/keywords/enum_.rs, src/keywords/format.rs, src/keywords/items.rs, src/keywords/legacy/type_draft_4.rs, src/keywords/mod.rs, src/keywords/type_.rs, src/schemas.rs
Resolves #49
- Fixes various formatting issues in debug representation of validators.
- Removes `Draft3` since it is not supported (hope to add it before the next release)
- Fixes a bug in `draft_from_url` where URLs should have `#` in them
It covers mostly:
- debug representation 
- no-op branches where the checked instance has a type to which the validator is not applicable
=> test: Add more tests

src/error.rs, src/keywords/max_items.rs, src/keywords/max_length.rs, src/keywords/max_properties.rs, src/keywords/min_items.rs, src/keywords/min_length.rs, src/keywords/min_properties.rs, src/lib.rs
In `maxItems`, `maxLength`, `maxProperties`, `minItems`, `minLength` and `minProperties` validators
A test is problematic since it will require a large object + 32-bit system to build & test
fixes #64
=> fix: Possible truncation & panic 

src/compilation.rs, src/error.rs, src/lib.rs, src/resolver.rs
=> fix: Handle errors instead of `unwrap`

.gitmodules
I just noticed this issue, while compiling a fork of your crate without TLS because I want to statically link it with musl. If you don't want to include this, that's fine from my side but it might make it easier for others to depend on git versions of your crate & forks.
=> chore: Convert gitmodule to https

src/error.rs, src/keywords/legacy/type_draft_4.rs, src/keywords/type_.rs, src/lib.rs, src/primitive_type.rs
The goal of this PR is to improve memory utilisation of `MultipleTypesValidator` as well as improving validation performance.
The validation performance is achieved by:
* replacing iteration over a `Vec` instance (data are into the heap) with bit operations
* ensuring that errors are as small as possible
Performance improvements have been measured by running the following
```bash
rm -rf target/criterion
git co -f 4cf7d8d
cargo bench "type_multiple"
git co -f 9437e9d
sleep 60  # To allow cooling down the laptop
cargo bench "type_multiple"
```
The raw output is available [here](https://gist.github.com/macisamuele/c01319c524b831061be0285e18458503)
Summary:
* ~21% improvement in compile time
* at least 12% improvement in validation time (it goes up to 34% as well)
NOTE: I've run a subset of …
=> Use BitMaps to validate multiple types

src/keywords/legacy/type_draft_4.rs, src/keywords/type_.rs, src/lib.rs, src/primitive_type.rs
`PrimitiveType` is 1 byte, `&PrimitiveType` is 8 bytes.
It would be more efficient if passed by value
=> chore: Cargo fmt & clippy

Cargo.toml, src/keywords/legacy/type_draft_4.rs, src/keywords/ref_.rs, src/keywords/type_.rs, src/primitive_type.rs
The goal of this PR is to reduce validation penalty performance while interacting with `$ref`s.
At the current state every time we're trying to validate such object we're actually re-building all the validators (which is essentially the compile part of the process).
I've tried to move validators build logic (currently in `RefValidator::ensure_validators`) into the compilation process, but it get's though due to potential circular dependencies with references.
In order to reduce the code changes and keep performances in consideration I'm opting for storing the validators behind a `RwLock`.
The decision of using it is mostly related to the fact that respect a `Mutex` it does have similar performances but at the same time allows multiple readers (in our case multiple parallel validations). …
=> $ref keyword caches built validators

src/compilation.rs, src/error.rs, src/keywords/enum_.rs, src/keywords/mod.rs
It makes it a bit more readable
=> chore: Use `to_string` instead of `format!`

.github/workflows/build.yml, benches/jsonschema.rs, draft/src/lib.rs
As above and also
Update benchmark names to allow easier filtering and focusing on type of action (ie. check benches only of the lib or for comparison with other libs)
=> feat: Allow github to run benchmarks if [bench] is present in the commit message

Cargo.toml, draft/Cargo.toml
Currently the library does define very tight dependencies and this is not common in libraries.
Libraries should be able to use any version of the dependencies that are compatible with the code.
Think about the case of: we're depending on `serde-json==1.0.48` and new versions are released (let's say `1.0.53`) and the new version does fix some bug or enhance performances.
With the current `Cargo.toml` definition users of `jsonschema` library will not have benefits of the `serde-json` improvements and even worst they might end-up with binaries that are embedding multiple version of the `serder-json` library.
For this reason we should describe what are the minimum versions required for the code to compile and perform properly (maybe we depend on an higher version due to bug fixes rather than …
=> style: A rust library should not pin exact versions (use bounds instead)

perf-helpers/.gitignore, perf-helpers/Cargo.toml, perf-helpers/run, perf-helpers/src/main.rs
The goal of this PR is to streamline the process of getting obtaining a flamegraph to focus optimisation efforts (as described on https://github.com/Stranger6667/jsonschema-rs/issues/91#issuecomment-633236132)
The `cargo-flamegraph` crate allows to run a binary with `perf`/`dtrace` (depending on the platform) and producing a SVG file containing the flamegraph.
In order to obtain it we need to have debug symbols in the release build (and the subproject takes care of that).
In order to make the tool easier to use I've ensured that `perf-helpers/src/main.rs` retrieves the schema and instance JSON representation at compile time, such that testing different combinations requires to modify the command to run instead of the file to compile.
The way of using it is
```sh
./perf-helpers/run …
```
=> Create perf-helpers subproject to help in running code profiling

CHANGELOG.md, src/keywords/additional_properties.rs
Since it is not clear when `Vec` will be more efficient & when `HashSet` I think we can start from an easy win and use the same data structure but without copying values. The validation stays the same, but the compilation is noticeable faster (15-20%)
=> perf: Replace `Map` with `BTreeSet`

CHANGELOG.md, Cargo.toml, src/keywords/exclusive_maximum.rs, src/keywords/exclusive_minimum.rs, src/keywords/maximum.rs, src/keywords/minimum.rs, src/lib.rs
Related - #84 
This PR does not include a fix for `multipleOf`, since it is more complex than I initially though
Performance is about the same (even better up to 15% in some cases)
=> fix: Precision loss in numeric validators

.github/workflows/python-release.yml, python/MANIFEST.in
The artifact upload has been centralised into a single job to ensure that we're not partially publishing artifacts as well as simplification to have a single PyPi interaction point.
Additional changes of this PR are:
* ensure that `build.rs` is present in the source distribution (addresses https://github.com/Stranger6667/jsonschema-rs/issues/112#issuecomment-643368821)
* wheels should be uploadable on PyPi
**NOTE**: They will also be available as build artifact in the github-actions interface
You can check the results on https://github.com/macisamuele/jsonschema-rs/runs/766206482 (the .github/workflows/python-release.yml wokflow file is the only modification respect the branch in this PR)
Fixes: #112
=> Fix python source distribution and wheel uploads from all the platforms

CHANGELOG.md, python/src/lib.rs, python/src/ser.rs, src/keywords/additional_items.rs, src/keywords/mod.rs
While working on https://github.com/macisamuele/jsonschema-equivalent I've noticed that having boolean schemas into `items` keyword result into an invalid schema, when instead it should be considered valid.
Example:
```json
{
"additionalItems": false,
"items": true
}
```
is considered an invalid schema but according to the [draft (section 6.4.1)](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.4.1)
> The value of "items" MUST be either a valid JSON Schema or an array of valid JSON Schemas.
and `true` or `false` are valid JSON Schemas.
The goal of this PR is to fix this.
PS: I'm aware that the example schema is unlikely to be composed by humans as it really is as restrictive as `true` schema, but it is still a possible valid schema.
=> fix: `items` allows the presence of boolean schemas

python/tests-py/test_suite.py, src/keywords/pattern.rs, src/resolver.rs, tests/test_suite.rs
The goal of this PR is to bump json-schema-test-suite.
NOTE: Tests of `resolver` needed to be updated in order to make them independent from the external testing suite (and so making easier future bumps)
I "just" copied the schema resulting from `load` without trying to simplify it to contain only the information useful for the test.
=> Bump json schema test suite

CHANGELOG.md, src/keywords/format.rs
The goal of this PR is to ensure that we have better association between formats and draft version.
Some formats are not available on all the supported drafts and by not managing this case we might end up validating foreign formats according to the drafts (ie. `idn-hostname` is not defined on draft 4 and draft 6).
This is an initial proposal, a more long-term solution (if we do expect many more drafts showing up) might be defining an order between drafts (`PartialOrd` trait) and ensure that certain formats are available only for a range of `Draft`s.
I've not implemented anything similar for now as the *exceptions* are not many (at least for now)
=> fix: Ensure that formats are applied only to correspondent drafts

Cargo.toml, src/keywords/format.rs, tests/test_suite.rs
The goal of this PR, as visible on the description, is to improve the correctness of `idn-hostname` format.
Checking around I found no perfect rust library that does this validation and implementing the whole RFC seems really out of scope.
Among the different available libraries (idna, unic-idna, unic-idna-punicode) `idna` seems the most maintained and accurate (allows us to remove two of the three optional ignored tests).
=> fix: Add `idna` dependency to improve idn-hostname format correctness

Cargo.toml, README.md, tests/test_suite.rs
The goal of this PR is to bump again `JSON-Schema-Test-Suite` and bump `json_schema_test_suite` dependency to allow regular expressions in the ignored tests
=> chore: Bump JSON-Schema-Test-Suite

python/CHANGELOG.md, python/src/lib.rs, python/tests-py/test_jsonschema.py
=> fix: Handle errors during conversion to `Value` instead of using `unwrap`

CHANGELOG.md, src/compilation/options.rs, src/content_encoding.rs, src/content_media_type.rs, src/error.rs, src/keywords/content.rs, src/lib.rs
The goal of this PR is to complete the feature proposal drafted in #129 
In order to simplify external crates to define methods for content encoding/media type support I've modified the signature such that `ValidationError` instances are created only within `jsonschema` crate instead of returned by the check/converter method.
This allows us to not do much work on exposing the all APIs of `ValidationError` (especially considering that it might change in the future).
I don't expect specific performance regressions, but I did not really tested them :)
=> Extend json schema options with content media type and content encoding

src/keywords/additional_properties.rs, src/keywords/all_of.rs, src/keywords/any_of.rs, src/keywords/contains.rs, src/keywords/content.rs, src/keywords/dependencies.rs, src/keywords/enum_.rs, src/keywords/exclusive_maximum.rs, src/keywords/exclusive_minimum.rs, src/keywords/max_items.rs, src/keywords/max_length.rs, src/keywords/max_properties.rs, src/keywords/maximum.rs, src/keywords/min_items.rs, src/keywords/min_length.rs, src/keywords/min_properties.rs, src/keywords/minimum.rs, src/keywords/multiple_of.rs, src/keywords/one_of.rs, src/keywords/pattern_properties.rs, src/keywords/required.rs, src/resolver.rs, src/validator.rs
This PR is mostly introducing stylistic changes aimed to have the code-base reflecting the common rust style.
```rust
if foo() {
return something;
}
return something_else;
```
can be written with a more idiomatic format
```rust
if foo() {
something
} else {
something_else
}
```
Few additional changes are:
* `Validate::validate` relies on the result of `Validate::is_valid`: This allows to reduce code-duplication and should help in terms of binary size
* Usage of iterators instead of `for` loops with inner results: This would allow for the same performance but with a more idiomatic style and would help in tuning more performance with parallel iterations if we can prove that this is beneficial (check contains and required files)
=> Reduce explicit returns

src/compilation/options.rs, src/keywords/content.rs, src/lib.rs, src/validator.rs
@Stranger6667 : Apology for the caused issue
In #132 I've added the support of optional (depending on testing environment) of certain clippy lint.
Unfortunately this was poorly done and as side effect was de-activating all the unit-tests 😢
To fix the issue this is the minimal diff (doc in [here](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute))
```diff
-#![cfg(not(test))]	
-#![allow(clippy::integer_arithmetic, clippy::unwrap_used)]	
+#![cfg_attr(not(test), allow(clippy::integer_arithmetic, clippy::unwrap_used))]
```
After tests have been re-activated I've found out that in the last few PRs (#133 and #134) there were some tests that were failing that have been fixed in this PR.
NOTE: src/validator.rs change is a revert of #134 change because certain …
=> fix: Ensure that tests are executed

Cargo.toml, src/error.rs, src/resolver.rs
With this PR, `reqwest`is an optional dependency. It is still a default feature, and it is also used from the dev profile.
The parts in the code that use `reqwest` are compiled either if the relative feature is used or if `cfg(test)`. However, there is still an issue if tests runs with `--no-default-features`, because `test_suite` is an integration test, therefore the `test` feature is not enabled and many tests fail.
If this behavior must be fixed, I am a bit unsure about the best solution. Surely one of them is making the tests inside the suite aware of the availability of `reqwest` in order to be automatically skipped, but I think that there should be a better way to handle the situation.
Closes #137
=> Make reqwest an optional dependency

CHANGELOG.md, python/CHANGELOG.md, src/keywords/additional_properties.rs, src/keywords/mod.rs, src/keywords/type_.rs, src/lib.rs, src/resolver.rs
=> fix: Integers not recognized as numbers when the `type` keyword is a list of multiple values

CHANGELOG.md, python/CHANGELOG.md, src/keywords/const_.rs, src/keywords/enum_.rs, src/keywords/helpers.rs, src/keywords/mod.rs, src/lib.rs
=> Fix value comparisons

CHANGELOG.md, python/CHANGELOG.md, src/keywords/format.rs
=> fix: Do not accept `date` strings with single-digit month and day values

CHANGELOG.md, benches/jsonschema.rs, python/CHANGELOG.md, src/keywords/enum_.rs, src/primitive_type.rs
Resolves #80.
For the benched case it gives 2 ns vs 12 ns and almost no visible change in the compilation speed (it will be more visible in larger enums though) and other cases don't seem to be affected as well.
=> perf: Enum validation performance

CHANGELOG.md, python/CHANGELOG.md, src/compilation/options.rs, src/resolver.rs
Resolves #75 
Even though this implementation clones the underlying schema, it is an improvement over the status quo. Working with references could be done separately, as it will likely require changes to `Resolver` itself.
Location-independent identifiers is a separate issue.
This mechanism can be used to store `http://json-schema.org/draft-04/schema` and others.
=> feat: Add cache for schemas

codecov.yaml
As the coverage impl is not stable, the checks are pretty useless
=> chore: Disable codecov action checks

CHANGELOG.md, python/CHANGELOG.md, src/resolver.rs
=> fix: Not necessary network requests for schemas with `$id` values with trailing `#` symbol

bindings/python/CHANGELOG.md, bindings/python/MANIFEST.in
That `canada.json` file is >5mb and it not needed for building the package
=> chore: Exclude JSON blobs from `sdist`

.gitmodules
This had been done in the past already (9a4f79af9841266c913d42adf7a70ed532d3a237), but it seems this was changed again in f5be9508d0182fa5f3f673e8e9dd1dcdb45e94ca. Was this on purpose?
Using SSH for the submodule url does not allow anonymous checkout. I am installing the python bindings via pip directly from the git repo while building a docker container. pip does checkout the submodules, too - but because it's in the docker container there are no ssh keys present and the checkout fails. Using https worked before.
=> Fetch git submodule with https instead of ssh

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/src/keywords/additional_properties.rs
=> fix: Skipped validation on an unsupported regular expression in `patternProperties`

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/src/primitive_type.rs
=> fix: Missing `array` type in error messages for `type` validators containing multiple values

CHANGELOG.md, bindings/python/CHANGELOG.md, bindings/python/Cargo.lock, bindings/python/src/lib.rs, bindings/python/tests-py/test_jsonschema.py, jsonschema/src/error.rs, jsonschema/src/paths.rs
Validation errors now include instance paths, in a form similar to the `jsonschema` Python package.
Resolves #144
=> Improve Python error messages

jsonschema/src/compilation/context.rs, jsonschema/src/compilation/mod.rs, jsonschema/src/error.rs, jsonschema/src/keywords/enum_.rs, jsonschema/src/keywords/multiple_of.rs, jsonschema/src/keywords/one_of.rs, jsonschema/src/lib.rs, jsonschema/src/paths.rs, jsonschema/src/primitive_type.rs
Fix some more warnings from the `nursery` set of lints
=> chore: Fix more `clippy` warnings

jsonschema/Cargo.toml, jsonschema/src/error.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/format.rs, jsonschema/src/keywords/pattern.rs, jsonschema/src/keywords/pattern_properties.rs
Uses [`fancy-regex`](https://docs.rs/fancy-regex/0.5.0/fancy_regex/) in place of [`regex`](https://docs.rs/regex/) for matching against all patterns in JSON schemas. 
`regex` is still used when [converting a RegEx for ECMA 262](https://github.com/duckontheweb/jsonschema-rs/blob/b689ac5b32c29db0a36cf7ad3890e78f0cea96e3/jsonschema/src/keywords/pattern.rs#L78) to take advantage of the `Regex::replace_all` method, which is not included in `fancy-regex`.  Since `fancy-regex` depends on `regex` anyway, this does not affect the final size of the compiled binary (thanks to [this commit](https://github.com/niklasfasching/check_timed_logs_fast/commit/fa2ec6ef77d3befd03d8674e0ceae24846b620a6) for the idea). 
I also removed the test from #214, since that pattern is supported in this PR.
=> Add support for look-around patterns using fancy-regex

jsonschema/Cargo.toml, jsonschema/src/keywords/pattern.rs, jsonschema/src/keywords/pattern_properties.rs
Bumps `fancy-regex` to v0.6.0 (which now implements `Display` for the `Regex` struct) so we can go back to using `Display` formatting (see [this comment](https://github.com/Stranger6667/jsonschema-rs/pull/220#discussion_r627744671) from #220).
=> chore: Use Display formatting for Regex

CHANGELOG.md, jsonschema/src/paths.rs
=> fix: Incorrect encoding of `/` and `~` characters in `fmt::Display` implementation for `JSONPointer`

bindings/python/CHANGELOG.md, bindings/python/src/lib.rs, bindings/python/tests-py/test_jsonschema.py
=> feat(python): Additional attributes for ValidationError

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/meta_schemas/draft4.json, jsonschema/meta_schemas/draft6.json, jsonschema/meta_schemas/draft7.json, jsonschema/src/lib.rs
=> fix: Allow using empty arrays or arrays with non-unique elements for the `enum` keyword in schemas

CHANGELOG.md, bindings/python/CHANGELOG.md, jsonschema/Cargo.toml, jsonschema/src/lib.rs
=> fix: Panic on incomplete escape sequences in regex patterns

.github/workflows/build.yml, CHANGELOG.md, jsonschema/Cargo.toml, jsonschema/benches/jsonschema.rs, jsonschema/benches/jsonschema_valid.rs, jsonschema/meta_schemas/draft2019-09/meta/applicator.json, jsonschema/meta_schemas/draft2019-09/meta/content.json, jsonschema/meta_schemas/draft2019-09/meta/core.json, jsonschema/meta_schemas/draft2019-09/meta/format.json, jsonschema/meta_schemas/draft2019-09/meta/meta-data.json, jsonschema/meta_schemas/draft2019-09/meta/validation.json, jsonschema/meta_schemas/draft2019-09/schema.json, jsonschema/src/compilation/options.rs, jsonschema/src/keywords/format.rs, jsonschema/src/lib.rs, jsonschema/src/schemas.rs, jsonschema/tests/test_suite.rs
Adds a new "draft201909" feature that allows us to run tests against the new draft. Once we have everything in place, the feature is going to be removed. At this point, it should be considered private and used only for testing.
=> chore: A stub support for Draft 2019-09 behind a feature flag

jsonschema/Cargo.toml, jsonschema/src/compilation/context.rs, jsonschema/src/compilation/mod.rs, jsonschema/src/compilation/options.rs, jsonschema/src/keywords/additional_items.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/all_of.rs, jsonschema/src/keywords/any_of.rs, jsonschema/src/keywords/contains.rs, jsonschema/src/keywords/dependencies.rs, jsonschema/src/keywords/if_.rs, jsonschema/src/keywords/items.rs, jsonschema/src/keywords/mod.rs, jsonschema/src/keywords/not.rs, jsonschema/src/keywords/one_of.rs, jsonschema/src/keywords/pattern.rs, jsonschema/src/keywords/pattern_properties.rs, jsonschema/src/keywords/properties.rs, jsonschema/src/keywords/property_names.rs, jsonschema/src/keywords/ref_.rs, jsonschema/src/lib.rs, jsonschema/src/output.rs, jsonschema/src/paths.rs, jsonschema/src/schema_node.rs, jsonschema/src/validator.rs, jsonschema/tests/output.rs
The 2020-12 spec specifies a few things that are relevant for this PR.
- A "basic" output format which specifies how errors and annotations from failing or successful validations respectively should be structured
- A detailed specification of what annotations should be produced by "applicator" keywords - which are effectively control flow operators such as `oneOf`
- Explicitly specifying that unknown keywords must be retained and made available as annotations. For example the schema `{"name": "string","character": "narrator"}` must produce the annotation `{"character":"annotation"}`
This has implications which have led to the changes in this PR. Most importantly, we must collect unmatched keywords and store them in the validator tree so we can later produce annotations based on them. This …
=> Output formats

CHANGELOG.md, jsonschema-test-suite/README.md, jsonschema/src/compilation/options.rs, jsonschema/src/keywords/format.rs, jsonschema/src/schemas.rs, jsonschema/tests/test_suite.rs
Prior to draft versions 2019-09, format validation is enabled by default (though should be able to be disabled), and vice versa afterword. This patch adds `should_validate_formats` to CompilationOptions to force the option one way or another.
If not specified, it will fallback to a default based on the draft version (enabled by default before draft 2019-09).
I also rolled a small typo fix into this PR in a separate commit, let me know if you'd like me to squash the commits, or if you'd like that as a separate PR, or something else.
Closes #261
=> Disable format validation

bindings/python/CHANGELOG.md, bindings/python/src/ser.rs, bindings/python/src/types.rs, bindings/python/tests-py/test_jsonschema.py
We use tuples for geographic coordinates and bounding boxes which doesn't seem to have a direct mapping in JSON Schema.
This pull requests converts the tuple into a list to fix `ValueError: Unsupported type: 'tuple'` when validating a object that contains a tuple.
```
{ "bbox": (1,2,3,4) }
```
=> fix: convert python tuples into lists

jsonschema/Cargo.toml
fixes #335 .
Otherwise, reqwest will always use default-tls which is the native-tls even if jsonschema `reqwest-rustls-tls` feature is specified.
=> Set default-features=false for reqwest

CHANGELOG.md, bindings/python/Cargo.toml, jsonschema/Cargo.toml, jsonschema/src/compilation/options.rs, jsonschema/src/error.rs, jsonschema/src/keywords/pattern.rs, jsonschema/src/keywords/ref_.rs, jsonschema/src/lib.rs, jsonschema/src/resolver.rs
A PR for #246. It does not touch on the `async` feature, but makes the library build on `wasm32-unknown-unknown` with `default-features = false` and enables my use-case in [taplo](https://github.com/tamasfe/taplo).
The `SchemaResolver` trait that is supposed to resolve external schemas by given URLs along with a `DefaultResolver` that does what was already implemented, and additionally also resolves `file` schemes via std.
I decided to just use `Arc<dyn SchemaResolver>` as it is only used by ref validators currently, and adding generics everywhere would've added too much complexity.
A `ValidationError::Resolver` variant was also added accordingly to report if any of the external resolutions failed.
A compiler option to set a custom resolver was also added.
The following features were …
=> feat: Custom Resolvers for external references

jsonschema/Cargo.toml
As of the latest master (778b424b3de65f2ed6df64a2558bde7341c0094b) the library does not compile with cargo `minimal-versions` for the default features:
```shell
cargo +nightly update -Z minimal-versions && cargo +nightly check
```
This PR:
- Specifies precise dependency versions in `Cargo.toml` (as discussed [here](https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277))
- Upgrades all dependancies to the latest compatible versions such that the test suite passes with `--all-features`
Note that I was not able to determine the minimal version updates to allow the library to build with `minimal-versions` and so I took the sledge-hammer approach and upgraded everything.
And finally, thank you for proving this library to the community!
=> fix!: specify precise dependency versions in `Cargo.toml` and upgrade all versions

CHANGELOG.md, README.md, jsonschema/Cargo.toml
To avoid validation errors caused by `reqwest` missing a TLS backend
Resolves #343
=> fix: Enable `reqwest/native-tls` by default

jsonschema/src/resolver.rs
Hi @Stranger6667,
I'm also using jsonschema-rs as a library, and needed to use `rustls` with URL schemas, as cross no longer bundles openssl which `native-tls` requires. 
As per the README, I explicitly enabled `reqwest` and `rustls` and disabled `native-tls` via `default-features = false` in my Cargo.toml file but I still got the compilation error.
```
jsonschema = { version = "0.15.1", features = [
"resolve-file",
"reqwest",
"rustls"
], default-features = false }
```
```
Compiling jsonschema v0.15.1
error: the `reqwest` feature does not enable HTTP schema resolving anymore, use the `resolve-http` feature instead
--> C:\Users\jsmith\.cargo\registry\src\github.com-1ecc6299db9ec823\jsonschema-0.15.1\src\resolver.rs:81:21
|
81 | ...   compile_error!("the `reqwest` feature does not enable …
```
=> Allow URL schema resolving with rustls

CHANGELOG.md, jsonschema/src/compilation/options.rs, jsonschema/src/keywords/format.rs
enable the possibility of treating the unknown formats as errors. Currently, all unknown formats are silently ignored.
The PR isn't a breaking change -the default behavior remains unchanged.
=> feat: optional unknown formats as compilation error

jsonschema/Cargo.toml
this eliminates the dependency on num 0.2.1, allowing the use of num 0.4.0
=> bump fraction from 0.10.0 to 0.11.0

jsonschema/src/keywords/multiple_of.rs
See https://doc.rust-lang.org/std/f64/constant.EPSILON.html
Updated to https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.EPSILON
=> chore: remove deprecated epsilon reference

.github/workflows/build.yml, jsonschema/Cargo.toml
I'm not very familiar with `ahash`, or WASM in general, but it seems like `ahash`'s default randomness source panics when run inside a WASM environment. This change should make it so that `jsonschema` uses the runtime randomness source by default, but will not require it when included with `default-features = false`.
=> Don't depend on a particular ahash rng

CHANGELOG.md, jsonschema/src/compilation/mod.rs, jsonschema/src/error.rs, jsonschema/src/keywords/additional_properties.rs, jsonschema/src/keywords/mod.rs, jsonschema/src/keywords/ref_.rs, jsonschema/src/keywords/unevaluated_properties.rs, jsonschema/src/lib.rs, jsonschema/src/paths.rs, jsonschema/src/properties.rs, jsonschema/src/schemas.rs, jsonschema/src/validator.rs, jsonschema/tests/test_suite.rs
Closes #288.
This PR adds support for `unevaluatedProperties` when using the `draft201909` or `draft202012` feature flags.
I took a somewhat similar approach to the Python code linked in the issue for this feature, where the validator for `unevaluatedProperties` uses a subvalidator for each relevant keyword -- `properties`, `patternProperties`, `dependentSchemas`, `$ref`, etc -- that performs the relevant logic for determining if the given schema for the keyword would evaluate the property.
Each subvalidator exposes an interface that looks a lot like the `Validate` trait, but is oriented towards checking solely if a property would be valid against the schema, and has an optional return value to indicate evaluated vs not evaluated. The validator code, overall, is a bit verbose, not unlike …
=> Add support for `unevaluatedProperties` + a few other changes.

jsonschema/src/keywords/unevaluated_properties.rs, jsonschema/src/lib.rs
Fixes #421.
As described in #421, my initial attempt at adding subschema validation handling in `unevaluatedProperties` was a brute-force approach that sufficed to pass the JSON Schema test suite, but didn't correctly evaluate real-world schemas/data.
Instead of only considering properties evaluated if the subschema they were part of was valid, taking into account the behavior of the validator keyword (i.e. `oneOf` can't have multiple matching subschemas), it took an approach of simply finding the first subschema which seemed to favorably evaluate/validate the property.
`SubschemaSubvalidator` has been changed in two significant ways:
- it now properly considers the validation type (i.e. `allOf` vs `oneOf`)
- it validates the entire instance before validating the property
In practice, …
=> fix: `unevaluatedProperties` doesn't correctly handle subschema validation

jsonschema-test-suite/proc_macro/Cargo.toml
`cargo test` fails with:
```
$ cargo test                                                                                                                                     master ✭
Compiling json_schema_test_suite_proc_macro v0.3.0 (/home/auke/projects/jsonschema-rs/jsonschema-test-suite/proc_macro)
Compiling jsonschema v0.17.1 (/home/auke/projects/jsonschema-rs/jsonschema)
error[E0432]: unresolved import `syn::ItemFn`
--> /home/auke/projects/jsonschema-rs/jsonschema-test-suite/proc_macro/src/lib.rs:41:37
|
41  | use syn::{parse_macro_input, Ident, ItemFn};
|                                     ^^^^^^ no `ItemFn` in the root
|
note: found an item that was configured out
--> /home/auke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-1.0.109/src/lib.rs:365:32
|
365 | …
```
=> Fix `unresolved import "syn::ItemFn"` when running tests

README.md
`cargo tests` depends on an external, undocumented dependency: the JSON Schema Test Suite.
This commit introduces instructions how to get test suite.
Without the test suite, `cargo test` fails with:
```bash
$ cargo test
error: custom attribute panicked
--> tests/test_suite.rs:5:1
|
5 | #[json_schema_test_suite("tests/suite", "draft4", {"optional_bignum_0_0", "optional_bignum_2_0"})]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: Tests directory not found: tests/suite/tests/draft4
```
Fixes #443
=> Document how to run tests

.github/workflows/python-release.yml
This updates the `python-release.yml` Actions workflow to build and publish wheels for ARM (aarch64 / amd64).
Note that the new "Install built wheel on ARM architecture" step could be omitted; it is only there to demonstrate that the wheel will install in the appropriate architecture.
Resolves #431.
Thanks!
=> Build aarch64 Python wheels

CHANGELOG.md, bindings/python/CHANGELOG.md, bindings/python/README.md, bindings/python/src/lib.rs, bindings/python/tests-py/test_jsonschema.py, jsonschema/src/compilation/options.rs, jsonschema/src/error.rs, jsonschema/src/keywords/format.rs
=> feat(python): Custom format checkers

jsonschema/src/output.rs
=> feat: add `ErrorDescription::into_inner`

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema/src/keywords/unevaluated_properties.rs
=> fix: Combination of `unevaluatedProperties` with `allOf` and `oneOf`

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema/src/keywords/format.rs
=> fix: ipv4 format validation

CHANGELOG.md, MIGRATION.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-referencing/src/anchors/keys.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-referencing/src/resolver.rs, crates/jsonschema-referencing/src/retriever.rs, crates/jsonschema-referencing/src/uri.rs, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/keywords/additional_properties.rs, crates/jsonschema/src/keywords/ref_.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/node.rs, crates/jsonschema/src/output.rs, crates/jsonschema/src/retriever.rs
=> fix: Panic on root $id without base

crates/jsonschema-py/tests-py/test_suite.py, crates/jsonschema-referencing/src/lib.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-referencing/src/resource.rs, crates/jsonschema-referencing/src/specification/mod.rs, crates/jsonschema-referencing/src/vocabularies.rs, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/keywords/mod.rs, crates/jsonschema/src/keywords/ref_.rs, crates/jsonschema/src/options.rs, crates/jsonschema/tests/suite.rs
=> feat: Basic support for vocabularies

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/keywords/ref_.rs
=> fix: Infinite recursion

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py
=> fix(python): Panic on initializing a validator

README.md
Hi @Stranger6667 ,
Just wanted to make sure it deeplinks to the one with the latest API.
Thanks!
=> docs: update qsv link to version with jsonschema 0.26.0

crates/jsonschema/src/node.rs
there's an optimization already for just one validator, perhaps, we should short-circuit as well as soon as one validator is not valid
=> perf: short-circuit SchemaNode.is_valid

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/options.rs
=> fix: Return "Unknown specification" error on `https`-prefixed `$schema` for Draft 4, 5, 6

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/README.md, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_retriever.py
=> feat(python): Custom retrievers for external references

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/README.md, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema/src/primitive_type.rs
```python
try:
jsonschema_rs.validate({"maxItems": 2}, [1,2,3])
except Exception as exc:
error = exc
print(a.kind.limit)
```
=> feat(python): Extend `ValidationErrorKind` with error-specific context

CHANGELOG.md, README.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/README.md, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_meta.py, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/lib.rs
=> feat: Add meta validators

CHANGELOG.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-referencing-testsuite-codegen/src/loader.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-testsuite-codegen/src/loader.rs, crates/jsonschema/src/ecma.rs, crates/jsonschema/src/keywords/content.rs, crates/jsonschema/src/keywords/format.rs, crates/jsonschema/src/keywords/one_of.rs, crates/jsonschema/src/keywords/ref_.rs, crates/jsonschema/src/validator.rs
=> fix: Resolving external references nested inside local references

CHANGELOG.md, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/options.rs
=> feat: Add `ValidationOptions::with_registry`

Cargo.toml, crates/benchmark-suite/Cargo.toml, crates/benchmark/Cargo.toml, crates/jsonschema-cli/Cargo.toml, crates/jsonschema-py/Cargo.toml, crates/jsonschema-referencing-testsuite-codegen/Cargo.toml, crates/jsonschema-referencing-testsuite-internal/Cargo.toml, crates/jsonschema-referencing-testsuite/Cargo.toml, crates/jsonschema-referencing/Cargo.toml, crates/jsonschema-testsuite-codegen/Cargo.toml, crates/jsonschema-testsuite-internal/Cargo.toml, crates/jsonschema-testsuite/Cargo.toml, crates/jsonschema/Cargo.toml, crates/testsuite-common/Cargo.toml
As the license file is present at the root of the repository, it isn't part of any crate on crates.io, as those lie in subfolders. Ensure this file is published by telling cargo where to find it.
=> Ensure license file is published with each crate

.github/workflows/ci.yml, CHANGELOG.md, MIGRATION.md, README.md, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/src/registry.rs, crates/jsonschema-py/src/retriever.rs, crates/jsonschema-referencing/Cargo.toml, crates/jsonschema-referencing/src/anchors/mod.rs, crates/jsonschema-referencing/src/error.rs, crates/jsonschema-referencing/src/lib.rs, crates/jsonschema-referencing/src/meta.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-referencing/src/retriever.rs, crates/jsonschema-referencing/src/uri.rs, crates/jsonschema/Cargo.toml, crates/jsonschema/src/compiler.rs, crates/jsonschema/src/keywords/ref_.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/options.rs, crates/jsonschema/src/retriever.rs, crates/jsonschema/src/validator.rs, crates/jsonschema/tests/suite.rs
Resolves #385 
```rust
let validator = jsonschema::async_validator_for(&schema).await?;
```
=> feat: Async retriever

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi
The new class `Registry` were missing from  type declarations.
This MR adds this into the `.pyi` file
=> fix(python): added missing Registry to type declarations

crates/jsonschema/src/ext/numeric.rs, crates/jsonschema/src/keywords/multiple_of.rs
It appears that multiple issues have been reported regarding the validation of multipleOf for floating-point values. I have also identified a problem with the initial implementation of the remainder calculation: on my system, several (newly added) tests fail. Although the code implies that the results should fall within an EPSILON tolerance, the deviations are substantial. When BigFraction is used instead, all tests pass successfully.
value: 12.2 multipleOf:0.1 remainder:0.9999999999999858
value: 47.498 multipleOf:0.0001 remainder:0.9999999999417923
value: 3.1254 multipleOf:0.0001 remainder:0.999999999996362
=> fix: multiple_of_float

crates/jsonschema-referencing/src/meta.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-referencing/src/resource.rs
This tweaks the meta-schemas logic related to building lazy-static registries, in order to avoid cloning all the inner JSON Values which already have `'static` lifetimes.
=> perf(referencing): avoid cloning static Values for meta-schemas

crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/src/ser.rs, crates/jsonschema-py/tests-py/test_jsonschema.py
Resolves #453
In the end I chose to always use the `value` property in both old and new style enums
=> feat: added support for string enums in object keys #453

CHANGELOG.md, crates/benchmark-suite/benches/boon.rs, crates/benchmark-suite/benches/jsonschema.rs, crates/benchmark-suite/benches/jsonschema_valid.rs, crates/benchmark-suite/benches/valico.rs, crates/benchmark/src/lib.rs, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/python/jsonschema_rs/__init__.pyi, crates/jsonschema-py/src/lib.rs, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema-referencing-testsuite-codegen/src/generator.rs, crates/jsonschema-testsuite-codegen/src/idents.rs, crates/jsonschema/benches/keywords.rs, crates/jsonschema/src/error.rs, crates/jsonschema/src/keywords/any_of.rs, crates/jsonschema/src/keywords/one_of.rs, crates/jsonschema/src/keywords/ref_.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/paths.rs, crates/jsonschema/src/retriever.rs, crates/jsonschema/tests/output.rs, crates/jsonschema/tests/suite.rs
Fixes https://github.com/Stranger6667/jsonschema/issues/649
Hi, thank you for this awesome library! We are currently using the Python `jsonschema` library, and we want to switch to the `jsonschema-rs`, but we are blocked by one missing feature, which is the context for the `anyOf` and `oneOf` validation. We are currently using the `context` present in the `anyOf` and `oneOf` to provide better errors for our end-users.
Now I do understand that collecting those additional errors for the context of `anyOf` and `oneOf` can have an impact on the performance, so I went with the route of minimizing additional allocations and code branches for the happy path by simply collecting those errors only in case of an error during the validation. This does mean that the validation is executed again in …
=> Add `context` field to `anyOf` and `oneOf` validation error

CHANGELOG.md, MIGRATION.md, crates/jsonschema-py/CHANGELOG.md, crates/jsonschema-py/tests-py/test_jsonschema.py, crates/jsonschema-referencing/src/anchors/keys.rs, crates/jsonschema-referencing/src/registry.rs, crates/jsonschema-referencing/src/resource.rs, crates/jsonschema/benches/location.rs, crates/jsonschema/src/keywords/const_.rs, crates/jsonschema/src/keywords/content.rs, crates/jsonschema/src/keywords/legacy/type_draft_4.rs, crates/jsonschema/src/keywords/required.rs, crates/jsonschema/src/keywords/type_.rs, crates/jsonschema/src/lib.rs, crates/jsonschema/src/node.rs, crates/jsonschema/src/paths.rs
=> fix: `instance_path` segments are now unescaped when iterating
